### ISSUE TITLE
AssertionError: path must be a string

### ISSUE THREAD

**Issue by NeilMD** [AhmedAli7O1/hapi-arch#7] opened 2017-04-25 15:52 UTC
[ SERVICES LOADER ] { AssertionError: path must be a string
    at Module.require (module.js:497:3)
    at require (internal/module.js:20:19)
    at modulesLoader.loadAll (/home/shinichi/Desktop/hapimvc/eli/node_modules/hapi-arch/lib/pluginsLoader.js:132:47)
    at _.forEach.file (/home/shinichi/Desktop/hapimvc/eli/node_modules/hapi-arch/lib/modulesLoader.js:26:27)
    at arrayEach (/home/shinichi/Desktop/hapimvc/eli/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/home/shinichi/Desktop/hapimvc/eli/node_modules/lodash/lodash.js:9359:14)
    at Object.loadAll (/home/shinichi/Desktop/hapimvc/eli/node_modules/hapi-arch/lib/modulesLoader.js:23:9)
    at loadServices (/home/shinichi/Desktop/hapimvc/eli/node_modules/hapi-arch/lib/pluginsLoader.js:129:21)
    at Object.register (/home/shinichi/Desktop/hapimvc/eli/node_modules/hapi-arch/lib/pluginsLoader.js:63:5)
    at Object.target [as register] (/home/shinichi/Desktop/hapimvc/eli/node_modules/hapi/node_modules/joi/lib/object.js:77:34)
    at each (/home/shinichi/Desktop/hapimvc/eli/node_modules/hapi/lib/plugin.js:318:14)
    at iterate (/home/shinichi/Desktop/hapimvc/eli/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/home/shinichi/Desktop/hapimvc/eli/node_modules/hapi/node_modules/items/lib/index.js:39:9)
    at module.exports.internals.Plugin.internals.Plugin.register (/home/shinichi/Desktop/hapimvc/eli/node_modules/hapi/lib/plugin.js:321:11)
    at Promise (/home/shinichi/Desktop/hapimvc/eli/node_modules/hapi/lib/promises.js:24:16)
    at Object.exports.wrap (/home/shinichi/Desktop/hapimvc/eli/node_modules/hapi/lib/promises.js:13:12)
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'path must be a string',
  generatedMessage: false }

I keep getting this error, why?

**Comment by AhmedAli7O1** [comment] 2017-04-25 17:55
I think the problem is that your services folder is empty, whch still shoud be fine. gor now "if this's the case" you can fix it by creating a service, I'll release a fix for this issue today.
please let me know if it was something. else, so I can release a fix for it, because it's currently working on my end in the dev as well as a productuon environment.
Thanks

**Comment by NeilMD** [comment] 2017-04-25 19:46
I do have a service the one that is installed by default in the pluginOne

**Closed** 2017-04-25 21:15 UTC

**Comment by AhmedAli7O1** [comment] 2017-04-25 21:19
@NeilMD I've fixed the issue, use latest and you should be fine.
feel free to re-open if it still occure.
